### ISSUE TITLE
Websocket Error

### ISSUE THREAD

**Issue by ItsElijahWood** [Beaux44/Keystroke-Display#3]
I downloaded the zip and unzipped it then created a browser source then set it as index.html. Then when I typed it just displayed "Websocket not connected"
![Screenshot 2024-07-09 213703](https://github.com/Beaux44/Keystroke-Display/assets/152716646/7b0c0551-171b-4bee-aa0f-a4382d776e32)
..

**Comment by Beaux44** [comment]
The browser source requires the local key server to be running to connect to it and receive the keypresses, there currently aren't any prebuilt binaries, so if you want to use it, you have to install the Rust programming language, and build and run it according to the instructions on the main page.
